about/urls.py
from django.urls import path
from about.views import * 

app_name = "about"

urlpatterns = [
    path("",about, name="home"),
    path("submit_testi", submit_testi, name="submit")
]

baranghandle/urls.py
from django.urls import path
from .views import * 

app_name = "barang"
# /
urlpatterns = [
    path("",homepage, name="home"),
    path("barang.json",homepage_json, name="home_json"),
    path("detail_barang/<slug_barang>", detail_barang, name="barang"),
    path("jual", jual_barang, name="jual"),
    path("get_barang", get_user_barang, name="get_barang"),
    path("list_barang", list_barang, name="listbarang"),
    path("pembelian", pembelian, name="pembelian"),
    path("pembelian.json", pembelian_json, name="pembelian_json"),
    path("beli/<slug_barang>", ke_pembelian, name="beli"),
]

praktikum/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import error_404
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.conf.urls import url

app_name = "root"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("baranghandle.urls")),
    path('account/', include('social_django.urls', namespace='social')),
    path('user/', include("userhandle.urls")),
    path('about/', include("about.urls")),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon/favicon.ico')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error_404

userhandle/urls.py
from django.urls import path
from userhandle.views import *
app_name = "user"

urlpatterns = [
    path("masuk", masuk_views, name="masuk"),
    path("daftar", daftar_views, name="daftar"),
    path("keluar", keluar_views, name="keluar"),
    path("profile/<username>", profile_views, name="profile"),
]

templates/base.html
{% load static %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/css?family=Sniglet" rel="stylesheet">
    {% block head %}{% endblock %}
</head>

<body style="font-family: 'Sniglet', cursive;">
    <ul id="dropdown1" class="dropdown-content">
        <li><a href="{% url 'barang:listbarang' %}">Daftar Penjualan</a></li>
        <li><a href="{% url 'barang:pembelian' %}">Daftar Pembelian</a></li>
    </ul>
    <nav>
        <!-- ada profile, list barang, keranjang, login, signup, logout -->
        <ul id="slide-out" class="sidenav">
            <li>
                <a href="/">
                    <span style="color: #80EEF5;">Re</span>
                    <span style=" margin-left: -6px;">Usable</span>
                </a>
            </li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'barang:listbarang' %}">Daftar Penjualan</a></li>
            <li><a href="{% url 'barang:pembelian' %}">Daftar Pembelian</a></li>
            <li><a href="{% url 'about:home' %}">About</a></li>
            <li><a href="{% url 'user:profile' username=request.user %}">Profile</a></li>
            <li><a href="{% url 'user:keluar' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'about:home' %}">About</a></li>
            <li><a href="{% url 'user:daftar' %}">Signup</a></li>
            <li><a href="{% url 'user:masuk' %}">Login</a></li>
            {% endif %}
        </ul>
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-medium-and-down" style="z-index:100"><i
                class="material-icons">menu</i></a>

        <div class="nav-wrapper" style="background-color: #418CE3;">
            <a href="/" class="brand-logo left hide-on-med-and-down" style="margin-left: 15px;">
                <span style="color: #80EEF5;">Re</span>
                <span style=" margin-left: -6px;">Usable</span>
            </a>
            <div class="coba" style="text-align: center">


                {% if user.is_authenticated %}
                <span style="font-size:2rem">Hello {{ user.username }}</span>
                <ul class="right hide-on-med-and-down">
                    <li><a href="{% url 'about:home' %}">About</a></li>
                    <li><a href="{% url 'user:profile' username=request.user %}">Profile</a></li>
                    <li><a href="{% url 'user:keluar' %}">Logout</a></li>
                    <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Barangku<i
                                class="material-icons right">arrow_drop_down</i></a></li>
                </ul>
                {% else %}
                <span style="font-size:2rem">Hello Guest</span>
                <ul class="right hide-on-med-and-down">
                    <li><a href="{% url 'about:home' %}">About</a></li>
                    <li><a href="{% url 'user:daftar' %}">Signup</a></li>
                    <li><a href="{% url 'user:masuk' %}">Login</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>


    {% block body %}{% endblock body %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/default-passive-events@1.0.10/dist/index.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
    {% block js %}{% endblock js %}

    {% block script %}{% endblock script %}

</body>

</html>

templates/error_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Reusable</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/css?family=Sniglet" rel="stylesheet">
</head>
<body style="font-family:'Sniglet', cursive;">
    <h1 class="center-align">Waduh kamu nyasar :(</h1>
</body>
</html>

templates/error_500.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Reusable</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/css?family=Sniglet" rel="stylesheet">
</head>
<body style="font-family:'Sniglet', cursive;">
    <h1 class="center-align">Waduh kamu nyasar :(</h1>
</body>
</html>