about/urls.py
from django.urls import path
from about.views import * 

app_name = "about"

urlpatterns = [
    path("",about, name="home"),
    path("submit_testi", submit_testi, name="submit")
]

baranghandle/urls.py
from django.urls import path
from .views import * 

app_name = "barang"
# /
urlpatterns = [
    path("",homepage, name="home"),
    path("barang.json",homepage_json, name="home_json"),
    path("detail_barang/<slug_barang>", detail_barang, name="barang"),
    path("jual", jual_barang, name="jual"),
    path("get_barang", get_user_barang, name="get_barang"),
    path("list_barang", list_barang, name="listbarang"),
    path("pembelian", pembelian, name="pembelian"),
    path("pembelian.json", pembelian_json, name="pembelian_json"),
    path("beli/<slug_barang>", ke_pembelian, name="beli"),
]

praktikum/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import error_404
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.conf.urls import url

app_name = "root"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("baranghandle.urls")),
    path('account/', include('social_django.urls', namespace='social')),
    path('user/', include("userhandle.urls")),
    path('about/', include("about.urls")),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon/favicon.ico')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error_404

templates/baranghanlde/detail_barang.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
<title>Detail Barang</title>
<link rel="stylesheet" href="{% static 'css/detail_barang.css' %}">
{% endblock %}

{% block body %}
<div class="row">
    <div class="col s0 m1"></div>
    <div class="col s12 m3 valign-wrapper foto">
        <img src="{{barang.base64_pic}}" id="barang_pic">
    </div>
    <div class="col s12 m7">
        <h1>{{barang.nama_barang}}</h1>
        <h2>Penjual : {{barang.penjual}}</h2>
        <h6>{{barang.deskripsi}}</h6>
        <div>
            <span>Harga : Rp. 
                <span>{{barang.harga}}</span>
            </span>
        </div>
    </div>
    <div class="col s6 m6 right-align">
        <a class="btn" href="{% url 'barang:home' %}"
            id="kembali_pencarian">Kembali ke
            Pencarian</a>
    </div>
    <div class="col s6 m6 left-align">
        <form method="POST" action="{% url 'barang:beli' slug_barang=barang.slug %}">
            {% csrf_token %}
            <input type="submit" class="btn" value="Beli" id="beli">
        </form>
    </div>
    {% if messages %}
    {% for message in messages %}
    <script>
        const pesan = "{{message}}";
        alert(pesan);
    </script>
    {% endfor %}
    {% endif %}


</div>
{% endblock body %}

{% block js %}{% endblock %}

templates/baranghanlde/homepage.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
<title>Reusable</title>
<link rel="stylesheet" href="{% static 'css/homepage.css' %}">
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="input-field col s12 m6 l6">
            <form id="formq" method="POST">
                <input type="text" name="q" placeholder="Cari berdasarkan nama barang" id="qinput">
                <button type="submit" class="btn" id="search1"><i
                        class="material-icons">search</i></button>
            </form>
        </div>
        <div class="input-field col s12 m6 l6">
            <form id="formcategory" method="POST">
                <select name="kategori" id="category">
                    <option value="" disabled selected>Cari berdasarkan Kategori</option>
                    <option value="Hobi">Hobi</option>
                    <option value="Kendaraan">Kendaraan</option>
                    <option value="Aksesoris">Aksesoris</option>
                    <option value="Alat Tulis">Alat Tulis</option>
                    <option value="Elektronik">Elektronik</option>
                    <option value="Pakaian">Pakaian</option>
                </select>
                <button type="submit" class="btn" id="search2"><i
                        class="material-icons">search</i></button>
            </form>

        </div>
    </div>

    <div id="divnya">
        <div id="isinya"></div>
    </div>

    <h1>Barang Terbaru</h1>
    <div class="loader">
        <div class="preloader-wrapper big active">
            <div class="spinner-layer spinner-blue-only">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row" id="divnya2">
    </div>
</div>
<div class="fixed-action-btn">
    <a class="btn-floating btn-large" href="{% url 'barang:jual' %}">
        <i class="large material-icons">mode_edit</i>
    </a>
</div>
{% csrf_token %}
{% endblock body %}

{% block js %}
<script src="{% static 'js/homepage.js' %}"></script>
{% endblock %}

templates/baranghanlde/jual.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Ayo Jual!</title>
<link rel="stylesheet" href="{% static 'css/jual.css' %}">
{% endblock %}
{% block body %}
<!-- -------------------------------------------------------------------------------- -->

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="wrap">
        <h1>Jual Barang Kamu</h1>
        <div class="row">
            <div class="col s12 m6 file-field input-field">
                <div class="container-circle">
                    <div id="input-img">
                        <h4>Input Your Image</h4>
                        <img id="img_id" src="">
                        <div id="edit-btn"><span><i class="material-icons">edit</i><p id="edit">Edit</p></span></div>
                        {{form.picture}}
                    </div>
                </div>
                <p>Harga : {{form.harga}}</p>
            </div>
            <div class="col s12 m6">
                <p>Nama : {{form.nama_barang}}</p>
                
                <div class="input-field">
                    
                    {{form.kategori_barang}}
                    
                    <label>Category</label>
                </div>
                <p>Deskripsi : {{form.deskripsi}}</p>
            </div>
            
        </div>
        <input class="btn" type="submit" value="Jual">
    </div>
    
</form>
<!-- -------------------------------------------------------------------------------- -->
{% endblock body %}


{% block js %}
<script src="{% static 'js/jual.js' %}"></script>
{% endblock js %}
    

templates/baranghanlde/list_barang.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
<title>List barang</title>
<link rel="stylesheet" href="{% static 'css/list_barang.css' %}">
{% endblock %}

{% block body %}
<div class="container">
    <h1 class="center-align">List Barang Kamu</h1>
    <div class="row" id="divnya"></div>
</div>
<div id="user" data="{{user.id}}"></div>
{% csrf_token %}
{% endblock body %}

{% block js %}
<script src="{% static 'js/list_barang.js' %}"></script>
{% endblock %}

templates/baranghanlde/list_keranjang.html
{% extends 'base.html' %}
{% load static %}
{% load staticfiles %}

{% block head %}
<title>List Pembelian</title>
<link rel="stylesheet" href="{% static 'css/list_keranjang.css' %}">
{% endblock %}

{% block body %}
<div class="container">
    <h1>Barang yang pernah kamu beli</h1>
    <div class="row" id="divnya"></div>
</div>
<div id="user" data="{{user.id}}"></div>
{% endblock body %}

{% block js %}
<script src="{% static 'js/list_keranjang.js' %}"></script>
{% endblock %}